package jet.learning.opengl.common;

import android.opengl.GLES32;

public interface GLenum {
    int GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102/*GLES32.GL_TEXTURE_2D_MULTISAMPLE_ARRAY*/;
    int GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009 /*GLES32.GL_TEXTURE_CUBE_MAP_ARRAY*/;
    int GL_TEXTURE_BUFFER = 0x8C2A /*GLES32.GL_TEXTURE_BUFFER*/;
    int GL_CLAMP_TO_BORDER = 0x812D /*GLES32.GL_CLAMP_TO_BORDER*/;
    int GL_TEXTURE_BORDER_COLOR = 0x1004 /*GLES32.GL_TEXTURE_BORDER_COLOR*/;
    int GL_TEXTURE_BUFFER_OFFSET = 0x919D /*GLES32.GL_TEXTURE_BUFFER_OFFSET*/;
    int GL_TEXTURE_BUFFER_SIZE = 0x919E /*GLES32.GL_TEXTURE_BUFFER_SIZE*/;
    int GL_TESS_CONTROL_SHADER = 0x8E88/*GLES32.GL_TESS_CONTROL_SHADER*/;
    int GL_TESS_EVALUATION_SHADER = 0x8E88/*GLES32.GL_TESS_EVALUATION_SHADER*/;
    int GL_GEOMETRY_SHADER = 0x8DD9/*GLES32.GL_GEOMETRY_SHADER*/;
}
